// Code generated by tygo. DO NOT EDIT.

//////////
// source: main.go

/**
 * @externalDocs.description	OpenAPI
 * @externalDocs.url			https://swagger.io/resources/open-api/
 */
export interface Env {
}
