// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int32       `json:"id"`
	Username string      `json:"username"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
}

type UserToken struct {
	ID     int32  `json:"id"`
	UserID int32  `json:"user_id"`
	Token  string `json:"token"`
}
